device: cuda

dataset:
  src_train: data/train.en
  tgt_train: data/train.de
  src_val: data/val.en
  tgt_val: data/val.de
  max_length: 100
  batch_size: 32

model_name: rnn

model:
  embed_size: 256
  hidden_size: 256
  num_layers: 1

training:
  epochs_cnt: 5

checkpoint_path: checkpoints/rnn_model
