device: cuda

dataset:
  src_train: data/train.en
  tgt_train: data/train.de
  src_val: data/val.en
  tgt_val: data/val.de
  max_length: 100

model_name: transformer

model:
  d_model: 512
  num_encoder_layers: 2
  num_decoder_layers: 2
  nhead: 8

training:
  batch_size: 32
  epochs_cnt: 2

checkpoint_path: checkpoints/transformer_model
